import os
import json
import random
import re
import argparse   # ← add this

def clean_netlist_content(content):
    """
    Clean netlist content by removing unwanted lines and replacing paths.
    
    Args:
        content: Raw netlist content string
        
    Returns:
        Cleaned netlist content
    """
    lines = content.split('\n')
    cleaned_lines = []
    
    for line in lines:
        # Skip lines that contain Windows file paths with .asc extension
        if re.search(r'[A-Z]:\\.*\.asc', line):
            continue
        
        # Skip "Generated by LTspice" lines
        if 'Generated by LTspice' in line:
            continue
        
        # Replace specific Windows user paths with generic PATH
        line = re.sub(
            r'C:\\Users\\[^\\]+\\AppData\\Local\\LTspice\\lib\\cmp\\',
            'PATH\\\\',
            line
        )
        
        # Also handle any other variations of user paths
        line = re.sub(
            r'C:\\Users\\[^\\]+\\AppData\\Local\\LTspice\\',
            'PATH\\\\',
            line
        )
        
        cleaned_lines.append(line)
    
    # Join lines and remove any leading/trailing empty lines
    cleaned_content = '\n'.join(cleaned_lines).strip()
    
    # Replace µ with u
    cleaned_content = cleaned_content.replace('µ', 'u')
    
    return cleaned_content

def create_dataset_from_netlists(folder_path, output_file):
    """
    Create a JSONL dataset from .net files in a folder.
    
    Args:
        folder_path: Path to folder containing .net files
        output_file: Output JSONL file path
    """
    
    # Question templates for variety
    templates = [
        "Give me {name} netlist",
        "Fetch me a {name}",
        "Can you get me a netlist for {name}",
        "Generate {name} IC netlist"
    ]
    
    dataset = []
    
    # Get all .net files from the folder
    net_files = [f for f in os.listdir(folder_path) if f.endswith('.net')]
    
    for net_file in net_files:
        # Extract IC/circuit name from filename (remove .net extension)
        ic_name = os.path.splitext(net_file)[0]
        
        # Read the netlist content
        file_path = os.path.join(folder_path, net_file)
        with open(file_path, 'r', encoding='utf-8') as f:
            netlist_content = f.read().strip()
        
        # Clean the netlist content
        netlist_content = clean_netlist_content(netlist_content)
        
        # Skip if content is empty after cleaning
        if not netlist_content:
            print(f"Warning: {net_file} resulted in empty content after cleaning, skipping...")
            continue
        
        # Randomly select one template for this netlist
        question = random.choice(templates).format(name=ic_name)
        
        # Create the data entry
        entry = {
            "ic": ic_name,
            "system": "You are an expert at generating LTspice netlists. Return ONLY the netlist with no extra text.",
            #"instruction": question,
            "input": question,
            "output": netlist_content
            
        }
        
        dataset.append(entry)
    
    # Write to JSONL file
    with open(output_file, 'w', encoding='utf-8') as f:
        for entry in dataset:
            f.write(json.dumps(entry) + '\n')
    
    print(f"Dataset created successfully!")
    print(f"Total entries: {len(dataset)}")
    print(f"Output file: {output_file}")

def clean_dataset_from_jsonl(input_file, output_file):
    """
    Read an existing JSONL, clean each entry's 'output' via clean_netlist_content(),
    and write only non‐empty cleaned entries to a new JSONL.
    """
    cleaned_count = 0
    with open(input_file, 'r', encoding='utf-8') as fin, \
         open(output_file, 'w', encoding='utf-8') as fout:
        for line in fin:
            line = line.strip()
            if not line:
                continue
            try:
                entry = json.loads(line)
            except json.JSONDecodeError:
                print(f"Warning: skipping invalid JSON line: {line}")
                continue
            raw = entry.get('output', '')
            cleaned = clean_netlist_content(raw)
            if not cleaned:
                print(f"Warning: empty cleaned output for instruction “{entry.get('instruction','')}”")
                continue
            entry['output'] = cleaned
            fout.write(json.dumps(entry, ensure_ascii=False) + '\n')
            cleaned_count += 1
    print(f"Cleaned {cleaned_count} entries and wrote to {output_file}")


def reformat_jsonl(input_file, output_file):
    """
    Reformats a JSONL file by moving 'instruction' content to 'input'
    and removing the original 'instruction' and empty 'input' keys.
    """
    reformatted_count = 0
    with open(input_file, 'r', encoding='utf-8') as fin, \
         open(output_file, 'w', encoding='utf-8') as fout:
        for line in fin:
            line = line.strip()
            if not line:
                continue
            try:
                entry = json.loads(line)
            except json.JSONDecodeError:
                print(f"Warning: skipping invalid JSON line: {line}")
                continue

            if 'instruction' in entry:
                new_entry = {
                    "system": entry.get("system", ""),
                    "input": entry["instruction"],
                    "output": entry.get("output", "")
                }
                fout.write(json.dumps(new_entry, ensure_ascii=False) + '\n')
                reformatted_count += 1
            else:
                # If the format is already correct or different, write it as is.
                fout.write(json.dumps(entry, ensure_ascii=False) + '\n')

    print(f"Reformatted {reformatted_count} entries and wrote to {output_file}")


def merge_functional_and_netlist_data(functional_questions_file, netlist_data_file, output_file):
    """
    Merges a JSONL file of functional questions with a JSONL file of netlists.

    Args:
        functional_questions_file (str): Path to the JSONL file with functional questions.
        netlist_data_file (str): Path to the JSONL file with ICs and their netlists.
        output_file (str): Path to the output merged JSONL file.
    """
    netlists_by_ic = {}
    
    # 1. Read all netlists and store them in a dictionary keyed by IC name.
    with open(netlist_data_file, 'r', encoding='utf-8') as f:
        for line in f:
            try:
                entry = json.loads(line)
                if 'ic' in entry and 'output' in entry:
                    netlists_by_ic[entry['ic']] = entry
            except json.JSONDecodeError:
                print(f"Warning: Skipping invalid JSON line in {netlist_data_file}: {line.strip()}")
                continue

    merged_dataset = []
    
    # 2. Process the functional questions file.
    with open(functional_questions_file, 'r', encoding='utf-8') as f:
        for line in f:
            try:
                q_entry = json.loads(line)
                ic_name = q_entry.get('ic')
                questions = q_entry.get('questions')

                # Find the corresponding netlist data for the IC
                if ic_name and questions and ic_name in netlists_by_ic:
                    netlist_entry = netlists_by_ic[ic_name]
                    for question in questions:
                        new_entry = {
                            "ic": ic_name,
                            "system": netlist_entry.get("system", "You are an expert at generating LTspice netlists. Return ONLY the netlist with no extra text."),
                            "input": question,
                            "output": netlist_entry.get("output", "")
                        }
                        merged_dataset.append(new_entry)
                else:
                    # This will skip entries like "Available ICs:" or ICs without a matching netlist
                    print(f"Info: Skipping IC '{ic_name}' from functional questions file (no matching netlist or invalid entry).")

            except json.JSONDecodeError:
                print(f"Warning: Skipping invalid JSON line in {functional_questions_file}: {line.strip()}")
                continue

    # 3. Add the original netlist data to the merged dataset
    merged_dataset.extend(netlists_by_ic.values())

    # 4. Write the merged dataset to the output file
    with open(output_file, 'w', encoding='utf-8') as f:
        for entry in merged_dataset:
            f.write(json.dumps(entry) + '\n')

    print(f"\nMerged dataset created successfully!")
    print(f"Total entries: {len(merged_dataset)}")
    print(f"Output file: {output_file}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Create, clean, or reformat LTspice netlist datasets")
    parser.add_argument("--net_folder", help="Folder containing .net files to create a dataset")
    parser.add_argument("--input_jsonl", help="Existing JSONL file to clean or reformat")
    parser.add_argument("--output", required=True, help="Output JSONL file path")
    parser.add_argument("--reformat", action="store_true", help="Reformat JSONL from instruction/input to just input")
    parser.add_argument("--merge", nargs=2, metavar=('QUESTIONS_JSONL', 'NETLISTS_JSONL'), help="Merge functional questions with netlist data")
    args = parser.parse_args()

    if args.merge:
        functional_file, netlist_file = args.merge
        merge_functional_and_netlist_data(functional_file, netlist_file, args.output)
    elif args.reformat:
        if not args.input_jsonl:
            parser.error("--reformat requires --input_jsonl")
        reformat_jsonl(args.input_jsonl, args.output)
    elif args.input_jsonl:
        clean_dataset_from_jsonl(args.input_jsonl, args.output)
    elif args.net_folder:
        create_dataset_from_netlists(args.net_folder, args.output)
    else:
        parser.error("Please specify an operation: --net_folder, --input_jsonl (for cleaning), --input_jsonl --reformat, or --merge")